# Generated by Django 3.2.7 on 2021-09-05 19:42

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import invoice2.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom')),
                ('company_vat', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Merci de renseigner un numéro de TVA valide. Format: BExxxxxxxxx', regex='^[A-Z]{2,4}(?=.{2,12}$)[-_\\s0-9]*(?:[a-zA-Z][-_\\s0-9]*){0,2}$')], verbose_name='TVA')),
                ('contact_first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Prénom')),
                ('contact_last_name', models.CharField(max_length=255, verbose_name='Nom')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse e-mail')),
                ('contact_phone', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Merci de renseigner le numéro de téléphone avec un indicatif international. Format: +32xxxxxxxxx.', regex='^\\+\\d{9,15}$')], verbose_name='Téléphone')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(default=invoice2.models.generate_invoice_number, max_length=255, unique=True, verbose_name='Numéro')),
                ('invoice_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date de facturation')),
                ('terms_payment', models.CharField(choices=[('15', '15 jours'), ('15_end', '15 jours fin de mois'), ('30', '30 jours'), ('30_end', '30 jours fin de mois'), ('60', '60 jours'), ('60_end', '60 jours fin de mois'), ('90', '90 jours'), ('90_end', '90 jours fin de mois'), ('cash', 'Au comptant')], default='15', max_length=25, verbose_name='Conditions de payement')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Réduction (en %)')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom')),
                ('company_vat', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Merci de renseigner un numéro de TVA valide. Format: BExxxxxxxxx', regex='^[A-Z]{2,4}(?=.{2,12}$)[-_\\s0-9]*(?:[a-zA-Z][-_\\s0-9]*){0,2}$')], verbose_name='TVA')),
                ('contact_first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Prénom')),
                ('contact_last_name', models.CharField(max_length=255, verbose_name='Nom')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse e-mail')),
                ('contact_phone', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Merci de renseigner le numéro de téléphone avec un indicatif international. Format: +32xxxxxxxxx.', regex='^\\+\\d{9,15}$')], verbose_name='Téléphone')),
                ('address_street', models.CharField(max_length=255, verbose_name='Rue')),
                ('address_street_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Numéro')),
                ('address_bp', models.CharField(blank=True, max_length=255, null=True, verbose_name='BP')),
                ('address_zipcode', models.CharField(max_length=5, verbose_name='Code postal')),
                ('address_city', models.CharField(max_length=255, verbose_name='Ville')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice2.customer', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('vat', models.PositiveIntegerField(default=21, verbose_name='TVA (%)')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Prix (HTVA)')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_description', models.TextField(verbose_name='Description')),
                ('product_quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('product_vat', models.PositiveIntegerField(default=21, verbose_name='TVA (%)')),
                ('product_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Prix (HTVA)')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice2.invoice', verbose_name='Facture')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice2.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Facture (Produit)',
                'verbose_name_plural': 'Facture (Produits)',
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_street', models.CharField(max_length=255, verbose_name='Rue')),
                ('address_street_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Numéro')),
                ('address_bp', models.CharField(blank=True, max_length=255, null=True, verbose_name='BP')),
                ('address_zipcode', models.CharField(max_length=5, verbose_name='Code postal')),
                ('address_city', models.CharField(max_length=255, verbose_name='Ville')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice2.customer', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
