# Generated by Django 3.2.7 on 2021-09-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_status',
            field=models.CharField(choices=[('waiting', 'En cours'), ('done', 'Payée')], default='waiting', max_length=25, verbose_name='Statut'),
        ),
    ]
